# Generated by Django 3.0.7 on 2020-07-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
