# Generated by Django 3.0.7 on 2020-07-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('manufactor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название производителя', max_length=200)),
                ('summary', models.CharField(help_text='Введите описание производителя', max_length=500)),
            ],
        ),
    ]
