# Generated by Django 3.0.7 on 2020-07-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactor',
            options={'ordering': ['name']},
        ),
    ]
