# Generated by Django 3.1 on 2020-09-23 18:33

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    managers_group = Group.objects.create(name=u'Managers')
    item_change_perm = Permission.objects.get(name='Can change item')
    item_delete_perm = Permission.objects.get(name='Can delete item')
    managers_group.permissions.add(item_change_perm)
    managers_group.permissions.add(item_delete_perm)


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.get(name='Can change item').delete()
    Permission.objects.get(name='Can delete item').delete()
    Group.objects.filter(name=u'Managers').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200923_2100'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
