# Generated by Django 3.0.7 on 2020-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200704_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название категории', max_length=200)),
                ('summary', models.CharField(help_text='Введите описание категории', max_length=500)),
                ('availability', models.BooleanField(default=False, help_text='Выберите если категория доступна')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
