# Generated by Django 3.1 on 2020-09-26 14:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_auto_20200923_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('mail_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Номер письма')),
                ('order_id', models.BigIntegerField(blank=True, null=True, verbose_name='Номер заказа')),
                ('subject', models.CharField(max_length=500, verbose_name='Тема письма')),
                ('body', models.TextField(max_length=1000, verbose_name='Тело письма')),
                ('is_send', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
