# Generated by Django 3.0.7 on 2020-07-04 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название продукта', max_length=200)),
                ('summary', models.CharField(help_text='Введите описание продукта', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=False, help_text='Выберите если продукт доступен')),
                ('quantity', models.IntegerField(help_text='Введите количество продукта')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category')),
                ('manufactor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Manufactor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
