# Generated by Django 3.0.7 on 2020-07-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200704_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['login']},
        ),
    ]
