# Generated by Django 3.0.7 on 2020-07-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('catalog', '0007_auto_20200704_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
