# Generated by Django 3.0.7 on 2020-07-05 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_customer_customerorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID', primary_key=True, serialize=False),
        ),
    ]
