# Generated by Django 3.0.7 on 2020-07-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200705_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_id',
            new_name='status',
        ),
    ]
