# Generated by Django 3.0.7 on 2020-07-05 17:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_order_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'Создан'), ('p', 'Оплачен'), ('d', 'Доставлен')], default='c', help_text='Статус заказа', max_length=1),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(help_text='Введите количество продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Item')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Order')),
            ],
        ),
    ]
