# Generated by Django 3.0.7 on 2020-07-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20200705_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
