# Generated by Django 3.0.7 on 2020-07-05 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0019_auto_20200705_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
