# Generated by Django 3.1 on 2020-08-22 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20200816_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2020, 8, 27), help_text='Дата доставки заказа', verbose_name='Дата доставки'),
        ),
    ]
