# Generated by Django 3.1 on 2020-08-25 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего просмотра'),
        ),
    ]
