# Generated by Django 3.1 on 2020-08-26 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20200825_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='counter_buy',
            field=models.BigIntegerField(default=0, verbose_name='Количество покупок'),
        ),
        migrations.AddField(
            model_name='item',
            name='counter_view',
            field=models.BigIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
